version: 2.1
jobs:
  build-common: &common-build
    docker:
      - image: node
    working_directory: ~/source
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
                npm ci
            fi
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          # ESLint only supports Node >=4
          command: |
            if node --version | grep -q '^v12'; then
                npm run lint
            fi
      - run:
          name: Test
          command: npm run test-check-coverage
      - run:
          name: Upload coverage report
          command: |
            if node --version | grep -q '^v12'; then
                bash <(curl -s https://codecov.io/bash) -F unit -s coverage/lcov.info
            fi

  node-8:
    <<: *common-build
    docker:
      - image: circleci/node:8

  node-10:
    <<: *common-build
    docker:
      - image: circleci/node:10

  node-12:
    <<: *common-build
    docker:
      - image: circleci/node:12



workflows:
  version: 2
  build:
    jobs:
      - node-8
      - node-10
      - node-12
